#!/usr/bin/env sh
set -eu

staged_files="$(git diff --cached --name-only --diff-filter=ACMR | grep -E '\.(cjs|mjs|js|jsx|ts|tsx|json|jsonc|css)$' || true)"

if [ -n "$staged_files" ]; then
  echo "$staged_files" | xargs bunx biome check --write
  echo "$staged_files" | xargs git add
fi

bun run lint
bun run typecheck
bun run test
